name: Publish NPM Package
on:
  release:
    types: [created]
  dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Package
        run: |
          yarn
          yarn rollup
          npm publish --access public
