name: Publish NPM Package
on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Check if OIDC token exists
        run: |
          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
            echo "no token"
            exit 1
          else
            echo "token present"
          fi

      - name: Decode OIDC token
        run: |
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" | cut -d. -f2 | base64 --decode | jq

      - name: Publish Package
        run: |
          yarn
          yarn rollup
          npm publish --access public
