name: Publish Storybook
on:
  pull_request:
    branches:
      - dev
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: |
          npm i
          npm i react react-dom
          npm run deploy-storybook -- --ci --source-branch dev
        env:
          GH_TOKEN: ${{ secrets.PAT }}
